on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build-git-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - name: source-version
        id: source-version
        run: echo "version=$(cat version)-devel" >> $GITHUB_OUTPUT
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: push-container-image
        with:
          image: git-workflows
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Containerfile
          directory: .
          addLatest: false
          tags: ${{ steps.source-version.outputs.version }}-devel
          buildArgs: VERSION="${{ steps.source-version.outputs.version }}-$(git rev-parse --short HEAD)"
#  notify:
#    name: Slack Notifications
#    runs-on: ubuntu-latest
#    if: ${{ failure() }}
#    needs:
#      - build-git-workflows
#    steps:
#      - name: Notify Slack channel on failure
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_ICON: https://avatars.githubusercontent.com/u/74975412?s=200&v=4
#          SLACK_USERNAME: ${{ github.repository }}
#          SLACK_COLOR: '#ff0033'
#          SLACK_FOOTER: ''